checkLinks=true
checkHTTPLinks=true
IECompatibilityEdge=true
cleaned=false
wikiTitle=Home
allowMediawiki=false
allowMarkdown=false
checkHTTPLinksPool=30
backgroundColor=#FFFFFF
backgroundGlobal=true
backgroundOpacity=100
forkParser=false
forkParserSplit=20
outputType=html
fullTextSearch=false
fullTextSearchCompressionLevel=normal
allowHTMLEntities=true
helpOptimizedForSwing=true
relaxedSyntax=false
resolveAPILinks=true
dynamicMaps=true
escapeNonUTF8=false
lightbox=false
hasNotesTooltips=true
locale=en
search=titles